-- Generated by tool/build-relay-installer.sh — do not edit.
-- Every line below is already in supabase/migrations/; this file only
-- concatenates them in order so they can be pasted in one go.
--
-- Paste into the Supabase SQL editor of your project, or run
-- `supabase db push` from supabase/, which applies the same files.
-- Re-running is safe: every statement is written to be idempotent, and
-- tool/relay-schema-verify.sh applies this bundle twice in a row over a
-- migrated schema holding a row of every kind before any release.

-- ============================================================
-- supabase/migrations/202608010001_mds_relay.sql
-- ============================================================
-- My Social Data Space: append-only MVP mailbox.
--
-- The mobile/web app receives only a publishable key. No service-role secret is
-- embedded in a client. PostgreSQL stores opaque signed events; every pod checks
-- the Ed25519 signature derived from author_did before writing to Drift.

create table if not exists public.mds_relay_events (
  sequence bigint generated always as identity primary key,
  event_id text not null unique,
  kind text not null check (kind in ('post', 'tombstone')),
  space_id text not null check (char_length(space_id) between 1 and 160),
  post_id text not null check (char_length(post_id) between 1 and 200),
  author_did text not null check (
    char_length(author_did) between 40 and 180
    and author_did ~ '^did:key:z[A-Za-z0-9_-]+$'
  ),
  event_at timestamptz not null,
  payload jsonb not null check (octet_length(payload::text) <= 262144),
  signature text not null check (char_length(signature) between 40 and 180),
  inserted_at timestamptz not null default now()
);

create index if not exists mds_relay_events_space_sequence_idx
  on public.mds_relay_events (space_id, sequence);

alter table public.mds_relay_events enable row level security;
revoke all on public.mds_relay_events from anon, authenticated;
grant select, insert on public.mds_relay_events to anon, authenticated;
grant usage, select on sequence public.mds_relay_events_sequence_seq to anon, authenticated;

drop policy if exists "mds relay events are publicly readable" on public.mds_relay_events;
create policy "mds relay events are publicly readable"
  on public.mds_relay_events for select
  to anon, authenticated
  using (true);

drop policy if exists "mds relay events are append only" on public.mds_relay_events;
create policy "mds relay events are append only"
  on public.mds_relay_events for insert
  to anon, authenticated
  with check (
    inserted_at <= now() + interval '1 minute'
    and event_at <= now() + interval '1 day'
    and event_at >= now() - interval '10 years'
  );

create table if not exists public.mds_relay_spaces (
  space_id text primary key,
  member_count integer not null default 0 check (member_count >= 0),
  definition jsonb not null check (octet_length(definition::text) <= 262144),
  updated_at timestamptz not null default now()
);

alter table public.mds_relay_spaces enable row level security;
revoke all on public.mds_relay_spaces from anon, authenticated;
grant select on public.mds_relay_spaces to anon, authenticated;

drop policy if exists "mds relay spaces are publicly readable" on public.mds_relay_spaces;
create policy "mds relay spaces are publicly readable"
  on public.mds_relay_spaces for select
  to anon, authenticated
  using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'post_media',
  'post_media',
  true,
  104857600,
  array[
    'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/heic', 'image/heif', 'image/avif',
    'video/mp4', 'video/quicktime', 'video/webm', 'video/x-matroska', 'video/x-m4v', 'video/3gpp',
    'audio/mpeg', 'audio/mp4'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "mds media is append only" on storage.objects;
create policy "mds media is append only"
  on storage.objects for insert
  to anon, authenticated
  with check (
    bucket_id = 'post_media'
    and name ~ '^sha256-[A-Za-z0-9_-]+$'
  );

-- Intentionally no UPDATE or DELETE client policies. Content-addressed media
-- and signed events are immutable; moderation/retention administration belongs
-- in a separately secured server process, never in a key shipped in the app.

-- ============================================================
-- supabase/migrations/202608020001_remove_fabricated_catalog_state.sql
-- ============================================================
-- Remove social state that older development seeds invented for bundled topic
-- structures. This is intentionally narrow: a count is reset only when it still
-- equals the exact old placeholder, and a steward is removed only when it still
-- equals the exact fictional DID. Real activity or a real founder survives.
with legacy(space_id, placeholder_members, placeholder_steward) as (
  values
    ('space_field_recordings_01', 412, 'did:mds:steward_quiet'),
    ('space_macro_kitchen_01', 2071, 'did:mds:steward_macro'),
    ('space_powerlifting_01', 1284, 'did:mds:steward_iron'),
    ('space_coffee_01', 863, 'did:mds:steward_crema')
)
update public.mds_relay_spaces as spaces
set
  member_count = case
    when spaces.member_count = legacy.placeholder_members then 0
    else spaces.member_count
  end,
  definition = (
    case
      when spaces.definition ->> 'steward_id' = legacy.placeholder_steward
        then spaces.definition - 'steward_id'
      else spaces.definition
    end
  ) - 'member_count' - 'post_count',
  updated_at = now()
from legacy
where spaces.space_id = legacy.space_id
  -- Only a row that still carries something to remove. Without this, every
  -- re-application of the series rewrote these rows' `updated_at` although
  -- nothing about them changed — "re-running only adds what is missing" was
  -- true of every file but this one.
  and (
    spaces.member_count = legacy.placeholder_members
    or spaces.definition ->> 'steward_id' = legacy.placeholder_steward
    or spaces.definition ? 'member_count'
    or spaces.definition ? 'post_count'
  );

-- ============================================================
-- supabase/migrations/202608030001_signed_authored_topics.sql
-- ============================================================
-- User-authored topic definitions are append-only and client-verifiable.
--
-- `mds_relay_spaces` remains the operator-curated catalog. Giving the
-- publishable client key UPDATE access to it would let any installation replace
-- any topic. Authored definitions therefore use immutable signed events, just
-- like posts and tombstones; every receiving pod verifies the steward DID
-- before the definition reaches local storage.

create table if not exists public.mds_relay_space_events (
  sequence bigint generated always as identity primary key,
  event_id text not null unique,
  space_id text not null check (
    char_length(space_id) between 1 and 160
    and space_id ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$'
  ),
  version integer not null check (version between 1 and 1000000),
  steward_did text not null check (
    char_length(steward_did) between 40 and 180
    and steward_did ~ '^did:key:z[A-Za-z0-9_-]+$'
  ),
  definition jsonb not null check (octet_length(definition::text) <= 262144),
  signature text not null check (char_length(signature) between 40 and 180),
  inserted_at timestamptz not null default now()
);

create index if not exists mds_relay_space_events_sequence_idx
  on public.mds_relay_space_events (sequence desc);

create index if not exists mds_relay_space_events_space_version_idx
  on public.mds_relay_space_events (space_id, version desc);

alter table public.mds_relay_space_events enable row level security;
revoke all on public.mds_relay_space_events from anon, authenticated;
grant select, insert on public.mds_relay_space_events to anon, authenticated;
grant usage, select on sequence public.mds_relay_space_events_sequence_seq
  to anon, authenticated;

drop policy if exists "mds authored topics are publicly readable"
  on public.mds_relay_space_events;
create policy "mds authored topics are publicly readable"
  on public.mds_relay_space_events for select
  to anon, authenticated
  using (true);

drop policy if exists "mds authored topics are append only"
  on public.mds_relay_space_events;
create policy "mds authored topics are append only"
  on public.mds_relay_space_events for insert
  to anon, authenticated
  with check (
    inserted_at <= now() + interval '1 minute'
  );

-- No UPDATE or DELETE policy. A revision is another signed version; the older
-- version remains auditable and a client accepts it only from the same steward.

-- ============================================================
-- supabase/migrations/202608040001_signed_engagement.sql
-- ============================================================
-- Likes and conversation messages are signed by the people who created them
-- and travel as append-only events. Neither rewrites somebody else's immutable
-- post envelope.
--
-- **Only ever widens the kind check.** Two later files widen it again
-- (`202608090001`, `202608110001`). Dropping and re-adding this narrower list
-- unconditionally made a re-application of the series — which the operator
-- bundle tells people is safe — fail on any relay already carrying a
-- `message_reaction`, `proposal` or `proposal_vote` row, and would have
-- narrowed the check on one that did not. So the check is replaced only when
-- it does not already admit every kind this file needs.

do $$
declare
  needed text[] := array['post', 'engagement', 'message', 'tombstone'];
  current_check text;
begin
  select pg_get_constraintdef(con.oid) into current_check
    from pg_constraint con
   where con.conrelid = 'public.mds_relay_events'::regclass
     and con.conname = 'mds_relay_events_kind_check';
  if current_check is not null and not exists (
    select 1 from unnest(needed) as kind
     where position('''' || kind || '''' in current_check) = 0
  ) then
    return;
  end if;

  alter table public.mds_relay_events
    drop constraint if exists mds_relay_events_kind_check;
  alter table public.mds_relay_events
    add constraint mds_relay_events_kind_check
    check (kind in ('post', 'engagement', 'message', 'tombstone'));
end
$$;

-- ============================================================
-- supabase/migrations/202608050001_reversible_topic_discovery.sql
-- ============================================================
-- Authored-topic publication is reversible without deleting its audit trail.
--
-- Old rows remain version-1 `publish` events at audience revision zero. New
-- clients sign action, monotonic audience revision and event time together with
-- the full definition. A later unlisting therefore outranks a delayed publish;
-- republishing requires a higher audience revision.

alter table public.mds_relay_space_events
  add column if not exists event_version integer not null default 1
    check (event_version in (1, 2)),
  add column if not exists action text not null default 'publish'
    check (action in ('publish', 'unlist')),
  add column if not exists publication_revision integer not null default 0
    check (publication_revision between 0 and 1000000000),
  add column if not exists event_at timestamptz;

alter table public.mds_relay_space_events
  drop constraint if exists mds_relay_space_events_reversible_shape;

alter table public.mds_relay_space_events
  add constraint mds_relay_space_events_reversible_shape check (
    (event_version = 1 and action = 'publish' and publication_revision = 0)
    or
    (
      event_version = 2
      and publication_revision > 0
      and event_at is not null
    )
  );

create index if not exists mds_relay_space_events_publication_idx
  on public.mds_relay_space_events
    (space_id, publication_revision desc, action asc, version desc, sequence desc);

-- No UPDATE or DELETE permission is added. Unlisting is another immutable,
-- steward-signed event and does not claim to erase copies peers already kept.

-- ============================================================
-- supabase/migrations/202608060001_data_requests.sql
-- ============================================================
-- Data requests and their answers (REQ-44).
--
-- **Applied and checked against PostgreSQL 16 on 2026-07-31**, not only written:
-- both tables are created with row-level security on, `anon` and
-- `authenticated` hold SELECT and INSERT and nothing else, and an `anon`
-- session was refused UPDATE and DELETE on a real row. The file also re-applies
-- cleanly, so a redeploy is not a failure. What that run could *not* cover is
-- PostgREST and Storage, which is what `tool/relay_smoke.dart` is for once this
-- reaches a Supabase project.
--
-- **Two tables that the server is not asked to police, and that is the design.**
-- There are no accounts here — the client key is publishable and anonymous — so
-- this database cannot authenticate a DID and cannot be asked to show a row only
-- to the right reader. A restriction it cannot enforce is not a restriction, and
-- writing one would have been theatre.
--
-- So both guarantees live in the payload instead:
--
--  * **who asked** is an Ed25519 signature over the request's own terms,
--    verified by every receiving pod before the request is stored. A row here
--    claiming somebody else's name never reaches a screen.
--  * **who may read an answer** is settled by encryption. The response payload
--    is sealed to the exchange key the request carried, so this table may be
--    read by anybody and still means nothing to them.
--
-- Both tables are append-only for the same reason `mds_relay_space_events` is:
-- giving the publishable key UPDATE would let any installation rewrite any
-- request — including the reply address, which is the one field worth stealing.

create table if not exists public.mds_relay_data_requests (
  sequence bigint generated always as identity primary key,
  request_id text not null unique,
  space_id text not null check (
    char_length(space_id) between 1 and 160
    and space_id ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$'
  ),
  requester_did text not null check (
    char_length(requester_did) between 40 and 180
    and requester_did ~ '^did:key:z[A-Za-z0-9_-]+$'
  ),
  -- The whole signed envelope, including the signature the client checks.
  payload jsonb not null check (octet_length(payload::text) <= 65536),
  -- Kept as a column as well as inside the payload so a closed request can be
  -- filtered out server-side instead of downloaded and discarded.
  expires_at timestamptz,
  inserted_at timestamptz not null default now()
);

create index if not exists mds_relay_data_requests_space_idx
  on public.mds_relay_data_requests (space_id, sequence desc);

alter table public.mds_relay_data_requests enable row level security;
revoke all on public.mds_relay_data_requests from anon, authenticated;
grant select, insert on public.mds_relay_data_requests to anon, authenticated;
grant usage, select on sequence public.mds_relay_data_requests_sequence_seq
  to anon, authenticated;

drop policy if exists "mds data requests are publicly readable"
  on public.mds_relay_data_requests;
create policy "mds data requests are publicly readable"
  on public.mds_relay_data_requests for select
  to anon, authenticated
  using (true);

drop policy if exists "mds data requests are append only"
  on public.mds_relay_data_requests;
create policy "mds data requests are append only"
  on public.mds_relay_data_requests for insert
  to anon, authenticated
  with check (inserted_at <= now() + interval '1 minute');

-- Answers.
--
-- `payload` holds a sealed envelope and nothing else legible: no entry ids, no
-- field names, no values. `responder_did` is in the clear because the requester
-- has to count distinct contributors, and because a request names its author
-- too — asymmetry there would be the first step back to a surveillance
-- relationship.
create table if not exists public.mds_relay_data_request_responses (
  sequence bigint generated always as identity primary key,
  response_id text not null unique,
  request_id text not null check (char_length(request_id) between 1 and 160),
  responder_did text not null check (
    char_length(responder_did) between 40 and 180
    and responder_did ~ '^did:key:z[A-Za-z0-9_-]+$'
  ),
  payload jsonb not null check (octet_length(payload::text) <= 1048576),
  inserted_at timestamptz not null default now()
);

create index if not exists mds_relay_data_request_responses_request_idx
  on public.mds_relay_data_request_responses (request_id, sequence desc);

alter table public.mds_relay_data_request_responses enable row level security;
revoke all on public.mds_relay_data_request_responses from anon, authenticated;
grant select, insert on public.mds_relay_data_request_responses to anon, authenticated;
grant usage, select on sequence public.mds_relay_data_request_responses_sequence_seq
  to anon, authenticated;

-- Readable by anybody, and that is safe *only* because the payload is sealed.
-- If a future change ever puts anything legible in this table, this policy is
-- the line that has to change with it.
drop policy if exists "mds request answers are publicly readable"
  on public.mds_relay_data_request_responses;
create policy "mds request answers are publicly readable"
  on public.mds_relay_data_request_responses for select
  to anon, authenticated
  using (true);

drop policy if exists "mds request answers are append only"
  on public.mds_relay_data_request_responses;
create policy "mds request answers are append only"
  on public.mds_relay_data_request_responses for insert
  to anon, authenticated
  with check (inserted_at <= now() + interval '1 minute');

-- No UPDATE or DELETE on either table. A withdrawn request stops being
-- announced by its author's client rather than being erased here, which is the
-- same best-effort shape as a tombstone: in a real peer network you can ask
-- somebody to forget something, you cannot make them.

-- ============================================================
-- supabase/migrations/202608070001_challenges.sql
-- ============================================================
-- Community contests and the entries in them (REQ-17).
--
-- **Two tables, because a contest is two different claims.** The creator signs
-- the rules once and they stay checkable for the contest's life; entering is
-- each participant's own signed claim. One table carrying both would mean
-- either the creator attesting other people's participation — the same mistake
-- as a topic signing its own member count — or a signature that the first join
-- invalidates.
--
-- Neither table asks this database to decide anything. `mds_relay_challenges`
-- holds rules that verify against the creator's DID, and
-- `mds_relay_challenge_entries` holds claims that verify against the
-- participant's. A row here that lies is refused by the receiving pod, not by a
-- policy, because an anonymous publishable key cannot authenticate a DID.
--
-- Append-only for the same reason as every other relay table: UPDATE with a
-- publishable key would let any installation rewrite any contest's measure or
-- window, which is the one thing somebody losing would most like to change.

create table if not exists public.mds_relay_challenges (
  sequence bigint generated always as identity primary key,
  challenge_id text not null unique,
  space_id text not null check (
    char_length(space_id) between 1 and 160
    and space_id ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$'
  ),
  created_by text not null check (
    char_length(created_by) between 40 and 180
    and created_by ~ '^did:key:z[A-Za-z0-9_-]+$'
  ),
  -- The signed envelope, minus its participant list: that is never the
  -- creator's to state, and the client strips it before publishing.
  payload jsonb not null check (octet_length(payload::text) <= 65536),
  closes_at timestamptz,
  inserted_at timestamptz not null default now()
);

create index if not exists mds_relay_challenges_space_idx
  on public.mds_relay_challenges (space_id, sequence desc);

alter table public.mds_relay_challenges enable row level security;
revoke all on public.mds_relay_challenges from anon, authenticated;
grant select, insert on public.mds_relay_challenges to anon, authenticated;
grant usage, select on sequence public.mds_relay_challenges_sequence_seq
  to anon, authenticated;

drop policy if exists "mds contests are publicly readable"
  on public.mds_relay_challenges;
create policy "mds contests are publicly readable"
  on public.mds_relay_challenges for select
  to anon, authenticated
  using (true);

drop policy if exists "mds contests are append only"
  on public.mds_relay_challenges;
create policy "mds contests are append only"
  on public.mds_relay_challenges for insert
  to anon, authenticated
  with check (inserted_at <= now() + interval '1 minute');

-- Entries.
--
-- Unique on (contest, participant) rather than on an id of its own: entering
-- twice is entering once, and the pair is what makes a retry after a dropped
-- connection the same claim instead of a second person.
create table if not exists public.mds_relay_challenge_entries (
  sequence bigint generated always as identity primary key,
  challenge_id text not null check (char_length(challenge_id) between 1 and 160),
  participant_did text not null check (
    char_length(participant_did) between 40 and 180
    and participant_did ~ '^did:key:z[A-Za-z0-9_-]+$'
  ),
  payload jsonb not null check (octet_length(payload::text) <= 8192),
  inserted_at timestamptz not null default now(),
  unique (challenge_id, participant_did)
);

create index if not exists mds_relay_challenge_entries_challenge_idx
  on public.mds_relay_challenge_entries (challenge_id, sequence desc);

alter table public.mds_relay_challenge_entries enable row level security;
revoke all on public.mds_relay_challenge_entries from anon, authenticated;
grant select, insert on public.mds_relay_challenge_entries to anon, authenticated;
grant usage, select on sequence public.mds_relay_challenge_entries_sequence_seq
  to anon, authenticated;

drop policy if exists "mds contest entries are publicly readable"
  on public.mds_relay_challenge_entries;
create policy "mds contest entries are publicly readable"
  on public.mds_relay_challenge_entries for select
  to anon, authenticated
  using (true);

drop policy if exists "mds contest entries are append only"
  on public.mds_relay_challenge_entries;
create policy "mds contest entries are append only"
  on public.mds_relay_challenge_entries for insert
  to anon, authenticated
  with check (inserted_at <= now() + interval '1 minute');

-- No UPDATE or DELETE on either. Leaving a contest is a local decision that
-- stops this pod being scored; it does not erase the signed claim that somebody
-- entered, any more than a tombstone erases a post from a pod that already has
-- it.

-- ============================================================
-- supabase/migrations/202608080001_remove_untouched_fixture_topics.sql
-- ============================================================
-- Remove the four example structures that an older deployment guide told
-- operators to seed as though they were live communities.
--
-- This is deliberately narrower than matching an id or display name. A row is
-- removed only when:
--   * its id and complete canonical JSONB fingerprint are the generated fixture;
--   * it still has no measured members; and
--   * nobody has published signed authored history for that id.
--
-- An operator revision, a real authored publication, or even one changed field
-- therefore survives. `md5(text)` is used only as an exact data fingerprint,
-- never as an authentication primitive.
with fixture(space_id, definition_fingerprint) as (
  values
    ('space_coffee_01', '1661bc9d4dbbb898887d60c7eed23fa4'),
    ('space_field_recordings_01', 'a53176a908b4737b6afeb1b531385097'),
    ('space_macro_kitchen_01', '9f9455e61d1c8a8b28351fb4c1c32d96'),
    ('space_powerlifting_01', '85b07718de213929babccc3de6875602')
)
delete from public.mds_relay_spaces as spaces
using fixture
where spaces.space_id = fixture.space_id
  and spaces.member_count = 0
  and md5(spaces.definition::text) = fixture.definition_fingerprint
  and not exists (
    select 1
    from public.mds_relay_space_events as authored
    where authored.space_id = spaces.space_id
  );

-- ============================================================
-- supabase/migrations/202608090001_message_reactions.sql
-- ============================================================
-- Reactions to conversation messages travel exactly as post engagements do:
-- signed, append-only, actor-scoped events. The server stores and serves; every
-- receiving pod verifies the signature and target before Drift sees the row.
--
-- Only ever widens the kind check, for the reason `202608040001` gives: a
-- later file (`202608110001`) widens it again, and re-applying this narrower
-- list over a relay that holds `proposal` rows failed outright.

do $$
declare
  needed text[] := array['post', 'engagement', 'message', 'message_reaction', 'tombstone'];
  current_check text;
begin
  select pg_get_constraintdef(con.oid) into current_check
    from pg_constraint con
   where con.conrelid = 'public.mds_relay_events'::regclass
     and con.conname = 'mds_relay_events_kind_check';
  if current_check is not null and not exists (
    select 1 from unnest(needed) as kind
     where position('''' || kind || '''' in current_check) = 0
  ) then
    return;
  end if;

  alter table public.mds_relay_events
    drop constraint if exists mds_relay_events_kind_check;
  alter table public.mds_relay_events
    add constraint mds_relay_events_kind_check
    check (kind in ('post', 'engagement', 'message', 'message_reaction', 'tombstone'));
end
$$;

-- ============================================================
-- supabase/migrations/202608100001_abuse_reports.sql
-- ============================================================
-- Reports travel to the operator of a configured community relay, and only
-- there. The queue is write-only for clients: anybody may file a report,
-- nobody may read the queue back, so a report cannot become a public accusation
-- or a way to enumerate what other people reported.

create table if not exists public.mds_abuse_reports (
  sequence bigint generated always as identity primary key,
  report_id text not null unique,
  subject text not null check (subject in ('post', 'message', 'account')),
  subject_id text not null check (char_length(subject_id) between 1 and 200),
  author_did text not null check (
    char_length(author_did) between 40 and 180
    and author_did ~ '^did:key:z[A-Za-z0-9_-]+$'
  ),
  reporter_did text not null check (
    char_length(reporter_did) between 40 and 180
    and reporter_did ~ '^did:key:z[A-Za-z0-9_-]+$'
  ),
  category text not null check (category in (
    'spam_or_scam', 'harassment', 'hate_speech',
    'sexual_content', 'violence_or_illegal', 'something_else'
  )),
  space_id text not null default '' check (char_length(space_id) <= 160),
  reported_at timestamptz not null,
  signature text not null check (char_length(signature) between 40 and 180),
  inserted_at timestamptz not null default now()
);

create index if not exists mds_abuse_reports_triage_idx
  on public.mds_abuse_reports (inserted_at desc, subject_id);

alter table public.mds_abuse_reports enable row level security;
revoke all on public.mds_abuse_reports from anon, authenticated;

-- Insert only. The operator reads this queue with the service role, out of band.
grant insert on public.mds_abuse_reports to anon, authenticated;
grant usage, select on sequence public.mds_abuse_reports_sequence_seq to anon, authenticated;

drop policy if exists "anyone may file a report" on public.mds_abuse_reports;
create policy "anyone may file a report"
  on public.mds_abuse_reports for insert to anon, authenticated with check (true);

-- ============================================================
-- supabase/migrations/202608110001_governance_exchange.sql
-- ============================================================
-- Community decisions and ballots travel as signed, append-only events like
-- everything else. The relay stores and serves; the receiving pod verifies the
-- proposer's signature and the ballot's credential before either may exist
-- there, so the relay is a carrier and never an authority on what a community
-- decided.
--
-- Only ever widens the kind check, like the two files before it. This one is
-- the widest today; guarding it too means a later file that adds a kind does
-- not turn a re-application of this one into the narrowing that failed before.

do $$
declare
  needed text[] := array[
    'post', 'engagement', 'message', 'message_reaction',
    'proposal', 'proposal_vote', 'tombstone'
  ];
  current_check text;
begin
  select pg_get_constraintdef(con.oid) into current_check
    from pg_constraint con
   where con.conrelid = 'public.mds_relay_events'::regclass
     and con.conname = 'mds_relay_events_kind_check';
  if current_check is not null and not exists (
    select 1 from unnest(needed) as kind
     where position('''' || kind || '''' in current_check) = 0
  ) then
    return;
  end if;

  alter table public.mds_relay_events
    drop constraint if exists mds_relay_events_kind_check;
  alter table public.mds_relay_events
    add constraint mds_relay_events_kind_check
    check (kind in (
      'post', 'engagement', 'message', 'message_reaction',
      'proposal', 'proposal_vote', 'tombstone'
    ));
end
$$;

-- ============================================================
-- supabase/migrations/202608120001_steward_report_mailbox.sql
-- ============================================================
-- Sealed steward reports, for a steward who is never on the same network
-- (QoL #3.4, the relay leg).
--
-- **Not modelled on `mds_relay_data_request_responses`, deliberately.** That
-- table carries `responder_did` as a cleartext column, and that is correct
-- there: `DataRequestResponse.responderDid` says so in its own words — the
-- requester is identified in the request, and hiding the answerer would be an
-- asymmetry on the way back to a surveillance relationship.
--
-- A report is the opposite. The entire point of #3.4 is that who reported whom
-- does not become knowable: the steward sees counts with a two-distinct-reporter
-- floor and never an identity. Copying the response table's shape would have put
-- the reporter's DID in the clear on a row anybody can read, handing the relay
-- operator precisely the fact the floor exists to withhold — while the steward,
-- the person actually entitled to act, still could not see it. So there is no
-- sender column here, and the payload is an `AnonymousDrop`, which has no sender
-- field at all. Authorship travels signed INSIDE the ciphertext and is checked
-- by the receiving pod against the identity that payload itself claims.
--
-- **What this table still discloses, stated rather than glossed.** There are no
-- accounts, so this database cannot authenticate a DID and cannot be asked to
-- show a row only to its recipient — the same honest limit the data-requests
-- migration records. Anyone who can read it therefore learns that SOMEBODY sent
-- a sealed thing to a given steward, and roughly when. They do not learn who,
-- what, about whom, or in which topic. Removing even that would need onion
-- routing this app does not have, and claiming otherwise in a comment would be
-- the kind of security theatre this file exists to avoid.
--
-- Append-only for the same reason as every other relay table: giving the
-- publishable key UPDATE would let any installation rewrite anybody's row.

create table if not exists public.mds_steward_report_mailbox (
  sequence bigint generated always as identity primary key,
  -- Routing, and the only identity here. Says a steward has post, never from
  -- whom.
  recipient_did text not null check (
    char_length(recipient_did) between 40 and 180
    and recipient_did ~ '^did:key:z[A-Za-z0-9_-]+$'
  ),
  -- The whole AnonymousDrop: recipient_did, epk, nonce, ciphertext, mac. No
  -- sender field exists in that shape, and the client pins its exact key set
  -- so one cannot be added by accident.
  payload jsonb not null check (octet_length(payload::text) <= 16384),
  inserted_at timestamptz not null default now()
);

-- A steward pulls only their own, newest first, without downloading the rest.
create index if not exists mds_steward_report_mailbox_recipient_idx
  on public.mds_steward_report_mailbox (recipient_did, sequence desc);

alter table public.mds_steward_report_mailbox enable row level security;
revoke all on public.mds_steward_report_mailbox from anon, authenticated;

-- SELECT and INSERT and nothing else. No UPDATE, no DELETE: a reporter cannot
-- retract an accusation from under a steward, and nobody can rewrite one into
-- something the sealed bytes do not say.
grant select, insert on public.mds_steward_report_mailbox to anon, authenticated;
grant usage, select on sequence public.mds_steward_report_mailbox_sequence_seq
  to anon, authenticated;

drop policy if exists "anyone may drop a sealed report" on public.mds_steward_report_mailbox;
create policy "anyone may drop a sealed report"
  on public.mds_steward_report_mailbox for insert to anon, authenticated with check (true);

-- Readable by anybody, and meaningless to everybody but the recipient. This is
-- the same bet the data-requests tables make and the reason it is safe to make
-- here: confidentiality is the payload's job, because it cannot be this
-- database's.
drop policy if exists "sealed reports are readable and unreadable"
  on public.mds_steward_report_mailbox;
create policy "sealed reports are readable and unreadable"
  on public.mds_steward_report_mailbox for select to anon, authenticated using (true);

-- ============================================================
-- supabase/migrations/202608130001_server_owned_relay_receipts.sql
-- ============================================================
-- Server-owned receipt time on every relay table (REQ-44 deadline authority).
--
-- **A default is not an authority.** Every table below declared
-- `inserted_at timestamptz not null default now()` and then granted `insert`
-- to `anon`, so the default only applies when the client omits the column. A
-- direct PostgREST writer can send `inserted_at` explicitly, and the append-only
-- policies bound it from *above* only — `inserted_at <= now() + interval '1
-- minute'` refuses a value from the future and accepts any value from the past.
--
-- That mattered the moment the client started treating this column as a
-- receipt. `SyncEngine._pullAnswers` judges a data request's deadline against
-- when the relay took custody of an answer, precisely because the responder's
-- own timestamp is a claim they control. Reading a column the responder can
-- also control would have moved the trust from one client-supplied value to
-- another while sounding like it had moved to the server.
--
-- So the value is taken out of the client's hands: a BEFORE INSERT trigger
-- overwrites whatever arrives with the server's own `now()`. `now()` rather
-- than `clock_timestamp()` so the stored value is exactly what the existing
-- append-only policies compare against, and transaction-consistent for a batch.
--
-- All eight tables, not only the one being read today. "The server owns
-- inserted_at" is either a property of this schema or it is a fact about one
-- table that the next person will generalise wrongly — and the contest
-- deadline is the next thing that wants a receipt it can trust.
--
-- Written as its own migration on the deployed-upgrade path rather than by
-- editing the originals: the tables already exist in the hosted project, and a
-- `create table if not exists` would not revisit them.

create or replace function public.mds_force_server_receipt()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- Unconditional. Checking "did the client supply one" would leave the
  -- backdating path open for every writer that omits the column and then
  -- updates it, and there is no legitimate caller that needs to choose this.
  new.inserted_at := now();
  return new;
end;
$$;

comment on function public.mds_force_server_receipt() is
  'Forces inserted_at to server time so a relay receipt cannot be backdated by its writer.';

do $$
declare
  required text[] := array[
    'mds_relay_events',
    'mds_relay_space_events',
    'mds_relay_data_requests',
    'mds_relay_data_request_responses',
    'mds_relay_challenges',
    'mds_relay_challenge_entries',
    'mds_abuse_reports',
    'mds_steward_report_mailbox'
  ];
  target text;
  missing text[] := '{}';
begin
  -- **Fail closed, and check everything before attaching anything.** The first
  -- version skipped a table that was absent, on the theory that a deployment
  -- part-way through the series should not be blocked. That theory is wrong
  -- here: all eight tables are created by migrations that precede this one, so
  -- an absent table does not mean "not yet" — it means the schema is not what
  -- this migration was written against. Skipping would report success while
  -- leaving that table's receipt client-writable, and because migrations run
  -- once it would never be revisited when the table appeared. A security
  -- upgrade that quietly covers seven of eight tables is worse than one that
  -- refuses, because only the refusal is visible.
  foreach target in array required
  loop
    if to_regclass('public.' || target) is null then
      missing := missing || target;
    end if;
  end loop;

  if array_length(missing, 1) is not null then
    raise exception
      'mds relay receipt triggers not installed: missing table(s) %',
      array_to_string(missing, ', ')
      using errcode = 'undefined_table';
  end if;

  foreach target in array required
  loop
    execute format(
      'drop trigger if exists mds_force_server_receipt on public.%I',
      target
    );
    execute format(
      'create trigger mds_force_server_receipt before insert on public.%I '
      'for each row execute function public.mds_force_server_receipt()',
      target
    );
  end loop;
end;
$$;

-- The append-only policies stay exactly as they were. They are no longer the
-- thing standing between a writer and a backdated receipt, but they still say
-- what the table accepts, and a policy that quietly disappeared alongside a new
-- trigger is how the next schema change loses a rule nobody remembers reading.

-- ============================================================
-- supabase/migrations/202608140001_immutable_challenge_claims.sql
-- ============================================================
-- One row per signed participation claim, so a withdrawal can travel (REQ-17).
--
-- **The hosted relay could not carry a leave, and the product says it can.**
-- `mds_relay_challenge_entries` was unique on `(challenge_id, participant_did)`
-- and the client writes with `resolution=ignore-duplicates`, so the first claim
-- a participant ever published won for good. Entering was reachable; leaving
-- was accepted locally, announced, and silently dropped. Every other pod kept
-- scoring somebody who had left. `Challenge.admits` deliberately admits a
-- withdrawal at any time before the contest closes, precisely because leaving
-- is supposed to work.
--
-- The fix keeps the append-only shape rather than trading it away. There is
-- still no UPDATE and no DELETE: a withdrawal is a *new immutable row*, and the
-- reader merges claims with `supersededBy` as it always has. What changes is
-- that the table stops collapsing two different signed statements into one.
--
-- **The signature is the identity of a claim.** It covers the contest, the
-- participant, the entry time, the active flag and the moment of change, so two
-- distinct statements cannot share one and a replay of the same statement
-- cannot produce a second row — which is what keeps its original server receipt
-- intact. `claim_id` is checked against the payload rather than trusted, so a
-- writer cannot file one claim under another's identity.

alter table public.mds_relay_challenge_entries
  add column if not exists claim_id text;

-- Backfill, fail-closed. A row whose payload carries no signature cannot be
-- given an identity here, and inventing one would let an unsigned legacy row
-- occupy the slot of a real claim. Refusing leaves the deployment on the old
-- schema, which is visibly broken rather than quietly wrong.
do $$
declare
  unsigned_rows bigint;
begin
  update public.mds_relay_challenge_entries
     set claim_id = payload->>'signature'
   where claim_id is null;

  select count(*) into unsigned_rows
    from public.mds_relay_challenge_entries
   where claim_id is null or claim_id = '';

  if unsigned_rows > 0 then
    raise exception
      'mds challenge claims not migrated: % row(s) carry no payload signature', unsigned_rows
      using errcode = 'data_exception';
  end if;
end;
$$;

alter table public.mds_relay_challenge_entries
  alter column claim_id set not null;

-- Enforced, not assumed: the column must be the signature the payload carries.
-- Without this a writer could publish somebody else's signed claim under a
-- claim id of its own choosing and take up a row that a real claim needs.
alter table public.mds_relay_challenge_entries
  drop constraint if exists mds_relay_challenge_entries_claim_id_matches_payload;
alter table public.mds_relay_challenge_entries
  add constraint mds_relay_challenge_entries_claim_id_matches_payload
  check (claim_id = payload->>'signature');

create unique index if not exists mds_relay_challenge_entries_claim_idx
  on public.mds_relay_challenge_entries (claim_id);

-- **Dropped last, and only once the replacement exists.** Until this goes, a
-- second claim by the same participant is still refused; after it, the unique
-- claim index is what stops a replay becoming a second row. Looked up by
-- catalogue rather than by guessed name, because the original was declared
-- inline and its generated name is not something to hard-code.
do $$
declare
  pair_constraint text;
begin
  -- Matched on the constraint's own definition rather than a guessed name: it
  -- was declared inline, so its generated name is not something to hard-code,
  -- and reading `conkey` back into column names needs a lateral join that a
  -- plain scalar subquery cannot express.
  select con.conname into pair_constraint
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public'
     and rel.relname = 'mds_relay_challenge_entries'
     and con.contype = 'u'
     and pg_get_constraintdef(con.oid) = 'UNIQUE (challenge_id, participant_did)'
   limit 1;

  if pair_constraint is not null then
    execute format(
      'alter table public.mds_relay_challenge_entries drop constraint %I',
      pair_constraint
    );
  end if;
end;
$$;

-- The receipt trigger from `202608130001` already covers this table, so each
-- new claim row gets its own server-owned `inserted_at` and a replay that the
-- unique claim index ignores keeps the receipt of the first.

-- ============================================================
-- supabase/migrations/202608170001_orphan_media_inventory.sql
-- ============================================================
-- My Social Data Space: an inventory of media objects nothing live refers to.
--
-- The event stream is append-only and the media bucket is insert-only for
-- client roles, so nothing a client can ever do removes stored bytes. Two
-- kinds of unreferenced object therefore accumulate on a deployed relay:
--
--   * media whose only referring post has been tombstoned — the author asked
--     for deletion and the signed tombstone landed, but the public bytes it
--     pointed at stayed served forever; and
--   * media stranded when an operator removes diagnostic rows, such as the
--     self-identifying `relay-smoke-…` trail `tool/relay_smoke.dart` leaves.
--
-- This function *names* those objects; it deletes nothing. Deletion must go
-- through the Storage API (`app/tool/relay_clean.dart` drives it), because
-- deleting rows from `storage.objects` directly strands the underlying bytes
-- in the storage backend instead of freeing them.
--
-- What a sweep can and cannot see, so an operator is not described a cleaner
-- service than they run:
--
--   * An object is "referenced" when its content id appears in a plaintext
--     signed payload: any non-tombstoned event, an authored topic revision, or
--     a cached topic definition. Content ids are `sha256-` plus unpadded
--     base64url, so the text they appear in never percent-encodes them.
--   * A sealed data-request answer is opaque by design, so a media address
--     that survives only inside one is invisible here and its object counts
--     as orphaned. Every such address originates from a post; if no live post
--     still carries it, the author deleted that post, and removing the media
--     is the deletion the tombstone promised.
--   * `older_than` exists because an upload precedes the signed event that
--     will reference it. The default hour is far beyond any client's
--     upload-to-publish gap.

create or replace function public.mds_relay_orphan_media(
  bucket text default 'post_media',
  older_than interval default interval '1 hour'
)
returns setof text
language sql
stable
security definer
set search_path = ''
as $$
  with live_text as (
    -- Every plaintext place a signed payload can carry a media address. A
    -- tombstone never keeps media alive, and neither does the post it
    -- retired: that pair is exactly what deletion means here.
    select e.payload::text as body
      from public.mds_relay_events e
     where e.kind <> 'tombstone'
       and not (
         e.kind = 'post'
         and exists (
           select 1
             from public.mds_relay_events t
            where t.kind = 'tombstone'
              and t.post_id = e.post_id
              and t.author_did = e.author_did
         )
       )
    union all
    select se.definition::text from public.mds_relay_space_events se
    union all
    select s.definition::text from public.mds_relay_spaces s
  )
  select o.name
    from storage.objects o
   where o.bucket_id = bucket
     and o.created_at < now() - older_than
     and not exists (
       select 1 from live_text where position(o.name in live_text.body) > 0
     )
$$;

comment on function public.mds_relay_orphan_media(text, interval) is
  'Names media objects no live signed payload references. Inventory only; '
  'deletion goes through the Storage API so the bytes are actually freed.';

-- Maintenance authority only. Client roles keep no execute: the sweep is an
-- operator action, and a publishable-key caller has no business enumerating
-- which public objects are about to disappear.
revoke all on function public.mds_relay_orphan_media(text, interval) from public;
revoke all on function public.mds_relay_orphan_media(text, interval) from anon, authenticated;
grant execute on function public.mds_relay_orphan_media(text, interval) to service_role;

-- ============================================================
-- supabase/migrations/202608180001_catalogue_search.sql
-- ============================================================
-- S-12: search past the bounded discovery window.
--
-- Clients filter with `definition->>name ilike` / `definition->>description
-- ilike` on both catalogue tables. Without trigram indexes every search is a
-- sequential scan of jsonb text extraction — fine at hundreds of topics,
-- misery at hundreds of thousands. pg_trgm turns the ilike into an index
-- seek; the expression indexes match the exact extraction the client sends.
create extension if not exists pg_trgm;

create index if not exists mds_relay_spaces_name_trgm_idx
  on public.mds_relay_spaces using gin ((definition->>'name') gin_trgm_ops);
create index if not exists mds_relay_spaces_description_trgm_idx
  on public.mds_relay_spaces using gin ((definition->>'description') gin_trgm_ops);

create index if not exists mds_relay_space_events_name_trgm_idx
  on public.mds_relay_space_events using gin ((definition->>'name') gin_trgm_ops);
create index if not exists mds_relay_space_events_description_trgm_idx
  on public.mds_relay_space_events using gin ((definition->>'description') gin_trgm_ops);

-- ============================================================
-- supabase/migrations/202608230001_expand_post_media_mime_types.sql
-- ============================================================
-- Studio accepts GIF/HEIC and common non-MP4 video containers, but the relay's
-- original bucket rejected them with 415. That left the post envelope local and
-- made attachments appear to fail at the reported >4 MB boundary even though
-- the actual rejection was the MIME contract. Update existing installations;
-- changing only the bootstrap migration would repair fresh relays and nobody
-- already running one.
update storage.buckets
set allowed_mime_types = array[
  'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/heic', 'image/heif', 'image/avif',
  'video/mp4', 'video/quicktime', 'video/webm', 'video/x-matroska', 'video/x-m4v', 'video/3gpp',
  'audio/mpeg', 'audio/mp4'
]
where id = 'post_media';

-- ============================================================
-- supabase/migrations/202608240001_relay_event_heads.sql
-- ============================================================
-- S-17: one tiny change check replaces one empty event-page request per joined
-- topic on every foreground tick. RLS still governs the underlying table and
-- the function reveals only the position already exposed by public event rows.
--
-- Dropped first, not `create or replace`d. `202608270001` widens this
-- function's result with a `total` column, and PostgreSQL refuses to change a
-- function's result type in place — so on any relay that had already run the
-- whole series, re-applying it (which the operator bundle tells people is
-- safe) stopped here with "cannot change return type of existing function".
-- The next file replaces this definition again; a client that calls it in
-- between gets the narrower result, which every client already reads.
drop function if exists public.mds_relay_event_heads(text[]);
create function public.mds_relay_event_heads(requested_space_ids text[])
returns table(space_id text, cursor text)
language sql
stable
security invoker
set search_path = ''
as $$
  select requested.space_id,
         max(events.sequence)::text as cursor
    from unnest(requested_space_ids) as requested(space_id)
    left join public.mds_relay_events as events
      on events.space_id = requested.space_id
   where char_length(requested.space_id) between 1 and 160
   group by requested.space_id
   limit 64;
$$;

revoke all on function public.mds_relay_event_heads(text[]) from public;
grant execute on function public.mds_relay_event_heads(text[]) to anon, authenticated;

-- ============================================================
-- supabase/migrations/202608270001_relay_event_heads_count.sql
-- ============================================================
-- The event-heads hint reports, per topic, the highest sequence AND the number
-- of rows. A row that commits late with a lower sequence (two writers, the
-- slower transaction landing behind the faster one) leaves the maximum where
-- it was; the count moves. A client that remembers the last head it acted on
-- and skips the page read only when the head is unchanged therefore fetches
-- exactly when something landed, including behind its cursor — which is what
-- the client's overlap re-read is for. Clients that read only `cursor` keep
-- working: the column set grows, its meaning does not change.
drop function if exists public.mds_relay_event_heads(text[]);
create function public.mds_relay_event_heads(requested_space_ids text[])
returns table(space_id text, cursor text, total bigint)
language sql
stable
security invoker
set search_path = ''
as $$
  select requested.space_id,
         max(events.sequence)::text as cursor,
         count(events.sequence) as total
    from unnest(requested_space_ids) as requested(space_id)
    left join public.mds_relay_events as events
      on events.space_id = requested.space_id
   where char_length(requested.space_id) between 1 and 160
   group by requested.space_id
   limit 64;
$$;
revoke all on function public.mds_relay_event_heads(text[]) from public;
grant execute on function public.mds_relay_event_heads(text[]) to anon, authenticated;

-- ============================================================
-- supabase/migrations/202609020001_private_message_mailbox.sql
-- ============================================================
-- Sealed private messages, for two people who are no longer on the same
-- network — the leg that makes a remembered contact reachable at all.
--
-- From the user: somebody met nearby is "remembered but not reachable via
-- normal internet", which left every private conversation dependent on both
-- phones being in the same place at the same time.
--
-- **Routed on an opaque address, not on a DID — the one thing that makes this
-- table different from `mds_steward_report_mailbox`.** That table carries
-- `recipient_did` in the clear and says plainly what it discloses: somebody
-- sent this steward something. For a steward that is an acceptable price. For
-- private messages between two people it is the social graph itself — who
-- writes to whom, how often, and, by counting distinct senders, how many
-- people somebody talks to. None of that is content, so sealing the payload
-- does not protect any of it.
--
-- So the routing key here is 32 bytes of randomness that one pod minted for
-- one contact and handed over in person, over an authenticated nearby session.
-- It names nobody. A second contact of the same person gets a different
-- address, so an operator reading this table cannot tell which addresses
-- belong to one person: they see many addresses receiving occasional sealed
-- bytes, and no way to group them.
--
-- **What this still discloses, stated rather than glossed.** There are no
-- accounts, so this database cannot authenticate anybody and cannot be asked
-- to show a row only to its reader — the same honest limit the data-request
-- and steward migrations record. Anyone who can read it learns that one
-- address received bytes at one time, and could correlate two addresses by
-- timing if they were watching for that. They do not learn who either party
-- is, what was said, or that any two addresses are related. Removing the
-- timing would need onion routing this app does not have, and claiming
-- otherwise in a comment would be the security theatre these files avoid.
--
-- **The address is a bearer name.** Anyone who learns one can drop at it and
-- read what is there, which is why confidentiality is the sealed payload's job
-- and never this table's, and why the address is unguessable rather than
-- derived from anything two people both know.
--
-- Append-only for the same reason as every other relay table: giving the
-- publishable key UPDATE or DELETE would let any installation rewrite or erase
-- anybody's post.

create table if not exists public.mds_private_message_mailbox (
  sequence bigint generated always as identity primary key,
  -- The opaque address, exactly as the pod mints it: 32 bytes base64url with
  -- the padding stripped. Pinned as a shape so a row addressed to something
  -- this app could never have minted cannot be written at all.
  inbox_id text not null check (inbox_id ~ '^[A-Za-z0-9_-]{43}$'),
  -- One `MailboxDrop`: epk, nonce, ciphertext, mac. Four keys, and not one of
  -- them a name — not in a column and not in the payload either. The app's
  -- ordinary `SealedEnvelope` carries `sender_did` and `recipient_did` in its
  -- JSON, which would have put the social graph in a row anybody can read
  -- while this comment promised otherwise. Authorship travels signed inside
  -- the ciphertext, verified by the receiving pod against the identity that
  -- payload itself claims, exactly as the steward mailbox does.
  --
  -- 256 KiB: a message body may be 128 KiB (`PersonText.messageBodyByteLimit`),
  -- which seals and base64-encodes to roughly 178 KiB with its envelope around
  -- it. Sized so that anything the app lets somebody write can actually be
  -- delivered — a smaller cap would send short messages and silently strand
  -- long ones.
  payload jsonb not null check (octet_length(payload::text) <= 262144),
  inserted_at timestamptz not null default now()
);

-- A pod collects one address at a time, oldest first, resuming from the last
-- sequence it acted on rather than re-reading the mailbox.
create index if not exists mds_private_message_mailbox_inbox_idx
  on public.mds_private_message_mailbox (inbox_id, sequence);

alter table public.mds_private_message_mailbox enable row level security;
revoke all on public.mds_private_message_mailbox from anon, authenticated;

-- SELECT and INSERT and nothing else. Without UPDATE nobody can rewrite a
-- sealed message into something the bytes do not say; without DELETE nobody
-- can remove somebody else's post before they collect it.
grant select, insert on public.mds_private_message_mailbox to anon, authenticated;
grant usage, select on sequence public.mds_private_message_mailbox_sequence_seq
  to anon, authenticated;

drop policy if exists "anyone may drop a sealed message" on public.mds_private_message_mailbox;
create policy "anyone may drop a sealed message"
  on public.mds_private_message_mailbox for insert to anon, authenticated with check (true);

-- Readable by anybody, and meaningless to everybody but the holder of the
-- address and the key. The same bet the steward mailbox makes, and safe for
-- the same reason: confidentiality is the payload's job, because it cannot be
-- this database's.
drop policy if exists "sealed messages are readable and unreadable"
  on public.mds_private_message_mailbox;
create policy "sealed messages are readable and unreadable"
  on public.mds_private_message_mailbox for select to anon, authenticated using (true);

-- ============================================================
-- supabase/migrations/202610030001_mailbox_read_by_secret.sql
-- ============================================================
-- Mailboxes are read by naming the address, never by listing the table.
--
-- **What the two mailbox migrations got wrong, stated rather than glossed.**
-- `202609020001_private_message_mailbox` routes on an address that is 32 bytes
-- of randomness, and its comments call that address unguessable. It is — and
-- then the same file granted `select ... using (true)` on the whole table, so
-- nobody had to guess: `GET /rest/v1/mds_private_message_mailbox?select=inbox_id`
-- handed every address to anybody holding the publishable key. With the list
-- in hand, one script could drop a million junk rows at every address; a pod
-- reads fifty drops per address per pass, oldest first, so a real message
-- queued behind them would wait months. And "a second contact of the same
-- person gets a different address, so an operator cannot group them" stopped
-- being true for anyone who could watch the list grow.
--
-- `202608120001_steward_report_mailbox` has the same shape for steward DIDs.
-- A DID is public anyway, so hiding it from a lister buys less — but the whole
-- table still listed who receives reports and how many, and it had no bound on
-- how many junk rows one stranger could leave for one steward.
--
-- **The fix keeps the address model and stops publishing it.**
--
--   * Table SELECT is revoked from the client roles. The address is what the
--     reader proves it knows: `mds_private_message_drops(address, after, limit)`
--     returns rows for exactly that address and nothing else. It is the same
--     bearer secret the reader already holds — the pod minted it and handed it
--     over in person — so no client key changes and no contact has to meet
--     again.
--   * Senders are untouched. They write to the address they were given, with
--     the same INSERT, exactly as before. A sender knowing an address is what
--     the design always assumed; what changes is that NOBODY ELSE can learn it
--     from this database.
--   * One address holds at most 1000 drops in any 24 hours (one steward DID,
--     likewise). Past that, an insert is refused with HTTP 429 and the sender's
--     pod keeps the message and tries again later. This is the bound on the
--     flood: whoever does know an address can delay that one channel by a day's
--     worth of junk, never by months. The number is mirrored by
--     `relayMailboxDropsPerWindow` in the client, which the tests pin to this
--     file.
--   * `inserted_at` on the private mailbox is now server-owned, as it already
--     was on the steward mailbox. A cap measured by a timestamp the writer
--     chooses is a cap the writer turns off by backdating.
--
-- **What this still does not hide**, so an operator is not described a better
-- service than they run: the operator's own maintenance role still reads every
-- row (sealed bytes and an address, as before), and anyone who learns one
-- address — the contact, or someone the contact leaked it to — can still drop
-- at it and read the sealed drops there. Confidentiality remains the payload's
-- job. A steward's DID is public, so anybody can still drop at, and fetch the
-- sealed drops for, a steward they can name; what they can no longer do is
-- enumerate every steward who receives reports.
--
-- **Compatibility.** App builds before 21 (versionCode) read both tables with a plain
-- SELECT. On a service with this migration those reads are refused (401), so
-- members on an older app stop collecting private messages and steward copies
-- until they update; their sending is unaffected. App 21 and later try the
-- functions first and fall back to the old SELECT when the function is missing
-- (404), so they keep working on a service that has not applied this file yet.
-- Apply it once your members are on 21 or later.
--
-- Idempotent like every other file here: rerunning the whole series in order
-- ends in this state, because this file runs after the two it amends.

-- --- the private message mailbox -------------------------------------------

drop policy if exists "sealed messages are readable and unreadable"
  on public.mds_private_message_mailbox;
revoke select on public.mds_private_message_mailbox from anon, authenticated;
-- INSERT stays, and so does the identity sequence it needs.
grant insert on public.mds_private_message_mailbox to anon, authenticated;
grant usage, select on sequence public.mds_private_message_mailbox_sequence_seq
  to anon, authenticated;

-- Server-owned custody time, with the same function every other relay table
-- uses (202608130001). Required by the cap below, not merely tidy.
drop trigger if exists mds_force_server_receipt on public.mds_private_message_mailbox;
create trigger mds_force_server_receipt
  before insert on public.mds_private_message_mailbox
  for each row execute function public.mds_force_server_receipt();

create index if not exists mds_private_message_mailbox_inbox_time_idx
  on public.mds_private_message_mailbox (inbox_id, inserted_at);

drop function if exists public.mds_private_message_drops(text, bigint, integer);
create function public.mds_private_message_drops(
  requested_inbox_id text,
  after_sequence bigint default null,
  page_limit integer default 50
)
returns table(sequence bigint, payload jsonb)
language sql
stable
security definer
set search_path = ''
as $$
  select m.sequence, m.payload
    from public.mds_private_message_mailbox as m
   -- The shape check first: anything that is not an address a pod could have
   -- minted names no mailbox, and is answered with nothing.
   where requested_inbox_id ~ '^[A-Za-z0-9_-]{43}$'
     and m.inbox_id = requested_inbox_id
     and m.sequence > coalesce(after_sequence, 0)
   order by m.sequence asc
   limit least(greatest(coalesce(page_limit, 50), 1), 50);
$$;

comment on function public.mds_private_message_drops(text, bigint, integer) is
  'Sealed drops for one contact address, oldest first, at most 50. The address '
  'is the reader''s proof; the table itself is not readable by client roles.';

revoke all on function public.mds_private_message_drops(text, bigint, integer) from public;
grant execute on function public.mds_private_message_drops(text, bigint, integer)
  to anon, authenticated;

-- --- the steward report mailbox ---------------------------------------------

drop policy if exists "sealed reports are readable and unreadable"
  on public.mds_steward_report_mailbox;
revoke select on public.mds_steward_report_mailbox from anon, authenticated;
grant insert on public.mds_steward_report_mailbox to anon, authenticated;
grant usage, select on sequence public.mds_steward_report_mailbox_sequence_seq
  to anon, authenticated;

create index if not exists mds_steward_report_mailbox_recipient_time_idx
  on public.mds_steward_report_mailbox (recipient_did, inserted_at);

drop function if exists public.mds_steward_report_drops(text, bigint, integer);
create function public.mds_steward_report_drops(
  requested_recipient_did text,
  after_sequence bigint default null,
  page_limit integer default 50
)
returns table(sequence bigint, payload jsonb)
language sql
stable
security definer
set search_path = ''
as $$
  select m.sequence, m.payload
    from public.mds_steward_report_mailbox as m
   where char_length(requested_recipient_did) between 40 and 180
     and requested_recipient_did ~ '^did:key:z[A-Za-z0-9_-]+$'
     and m.recipient_did = requested_recipient_did
     and m.sequence > coalesce(after_sequence, 0)
   order by m.sequence asc
   limit least(greatest(coalesce(page_limit, 50), 1), 50);
$$;

comment on function public.mds_steward_report_drops(text, bigint, integer) is
  'Sealed steward copies for one recipient DID, oldest first, at most 50. The '
  'table itself is not readable by client roles, so recipients cannot be listed.';

revoke all on function public.mds_steward_report_drops(text, bigint, integer) from public;
grant execute on function public.mds_steward_report_drops(text, bigint, integer)
  to anon, authenticated;

-- --- the per-address flood cap ----------------------------------------------

-- One function for both tables: the routing column is the only difference.
-- SECURITY DEFINER because the inserting role can no longer read the table it
-- is counting. The advisory lock serialises writers to one address, so two
-- concurrent floods cannot both read 999 and both insert.
create or replace function public.mds_mailbox_drop_cap()
returns trigger
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  cap constant integer := 1000;
  window_length constant interval := interval '24 hours';
  route text;
  recent integer;
begin
  if tg_table_name = 'mds_private_message_mailbox' then
    route := new.inbox_id;
    perform pg_advisory_xact_lock(hashtextextended('mds_private_message_mailbox:' || route, 0));
    select count(*) into recent
      from (
        select 1
          from public.mds_private_message_mailbox as m
         where m.inbox_id = route
           and m.inserted_at > now() - window_length
           -- Rows written before custody time was server-owned may carry any
           -- timestamp; one claiming the future must not hold the cap shut.
           and m.inserted_at <= now()
         limit cap
      ) as within_window;
  elsif tg_table_name = 'mds_steward_report_mailbox' then
    route := new.recipient_did;
    perform pg_advisory_xact_lock(hashtextextended('mds_steward_report_mailbox:' || route, 0));
    select count(*) into recent
      from (
        select 1
          from public.mds_steward_report_mailbox as m
         where m.recipient_did = route
           and m.inserted_at > now() - window_length
           and m.inserted_at <= now()
         limit cap
      ) as within_window;
  else
    raise exception 'mds_mailbox_drop_cap is attached to an unexpected table %', tg_table_name;
  end if;

  if recent >= cap then
    -- PostgREST answers a PTxyz state with HTTP xyz. 429 is what the client
    -- already reads as "not now": the message stays on the sender's pod and is
    -- offered again on a later pass, rather than being reported as refused.
    raise sqlstate 'PT429'
      using message = 'this mailbox is full for now',
            detail = 'at most 1000 drops per address in 24 hours';
  end if;
  return new;
end;
$$;

comment on function public.mds_mailbox_drop_cap() is
  'Refuses a mailbox drop with HTTP 429 once one address holds 1000 drops from '
  'the last 24 hours, bounding how far junk can push a real message back.';

-- Named roles too: a hosted project's default privileges grant EXECUTE on new
-- functions to the client roles directly, which a revoke from PUBLIC misses.
revoke all on function public.mds_mailbox_drop_cap() from public, anon, authenticated;

drop trigger if exists mds_mailbox_drop_cap on public.mds_private_message_mailbox;
create trigger mds_mailbox_drop_cap
  before insert on public.mds_private_message_mailbox
  for each row execute function public.mds_mailbox_drop_cap();

drop trigger if exists mds_mailbox_drop_cap on public.mds_steward_report_mailbox;
create trigger mds_mailbox_drop_cap
  before insert on public.mds_steward_report_mailbox
  for each row execute function public.mds_mailbox_drop_cap();

-- PostgREST caches the schema; without this the new functions answer 404
-- until its next reload, and app 21 would fall back to the SELECT this file
-- just revoked.
notify pgrst, 'reload schema';
